# Numpy
- 將中長跑距離由公里換算為英里
- 建立 ndarray 的方法
- ndarray 的特性
- 選擇 ndarray 的元素
- 常用的屬性
- 常用的方法
- ndarray 與基礎線性代數

## 將中長跑距離由公里換算為英哩
- 想把這幾個距離從公里換算成英里
```python
km_lst = [1.6, 3, 5, 10, 21, 42.195]
km_to_mile = 0.62137
```

### 使用 for 迴圈

In [1]:
km_lst = [1.6, 3, 5, 10, 21, 42.195]
km_to_mile = 0.62137
mile_lst = []
for km in km_lst:
    mile_lst.append(km * km_to_mile)
print(mile_lst)

[0.994192, 1.86411, 3.1068499999999997, 6.213699999999999, 13.04877, 26.21870715]


### 使用 map 與 lambda 函數

In [2]:
mile_lst = map(lambda x: x * km_to_mile, km_lst)
print(list(mile_lst))

[0.994192, 1.86411, 3.1068499999999997, 6.213699999999999, 13.04877, 26.21870715]


### 載入 Numpy

In [4]:
import numpy as np
km_lst = [1.6, 3, 5, 10, 21, 42.195]
km_to_mile = 0.62137
km_arr = np.array(km_lst)
# print(type(km_arr))
print(km_arr * km_to_mile)

[ 0.994192    1.86411     3.10685     6.2137     13.04877    26.21870715]


### 載入 NumPy 中的一個方法

In [10]:
from numpy import array

km_arr = array(km_lst)
print(type(km_arr))

<class 'numpy.ndarray'>


### 計算五個人的 BMI（練習）
```python
heights = [173, 168, 171, 189, 179]
weights = [65.4, 59.2, 63.6, 88.4, 68.7]
```

In [13]:
# 在這裡寫出您的答案
import numpy as np

heights = [173, 168, 171, 189, 179]
weights = [65.4, 59.2, 63.6, 88.4, 68.7]
heights_arr = np.array(heights)
weights_arr = np.array(weights)
bmi_arr = weights_arr / (heights_arr / 100)**2
print(bmi_arr)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


### 建立 ndarray 的方法
- np.array()
- np.arange()
- np.linspace()
- np.ones() 與 np.zeros()
- np.random.randint()

In [ ]:
import numpy as np

In [14]:
# np.arange()
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [18]:
# np.linspace()
arr = np.linspace(1, 10, 19)
print(arr)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [20]:
# np.ones()
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [22]:
# np.zeros()
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [27]:
# dtype 參數
arr = np.zeros(10, dtype = 'int')
arr = np.ones(10, dtype = 'complex')
arr = np.array([1, 0, 1], dtype = 'bool')
arr = np.array([1, 0, 1], dtype = 'str')
print(arr)

['1' '0' '1']


In [31]:
# np.random.randint()
arr = np.random.randint(1, 11, size = 10)
print(arr)

[ 3  2 10  6  8  6  9  1  8  1]


### ndarray 的特性
- 索引值
- 判斷條件

In [35]:
my_lst = [87, True, 'Tony']
for i in my_lst:
    print(type(i))

<class 'int'>
<class 'bool'>
<class 'str'>


In [36]:
arr = np.array(my_lst)
for i in arr:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### 選擇 ndarray 的元素
- 索引值
- 判斷條件

In [38]:
arr = np.arange(11, 21)
print(arr)
print(arr[0])
print(arr[1])
print(arr[-1])
print(arr[::2])
print(arr[[0, 1, -1]])

[11 12 13 14 15 16 17 18 19 20]
11
12
20
[11 13 15 17 19]
[11 12 20]


In [41]:
print(arr[arr > 15])

[16 17 18 19 20]


### 常用的屬性
- .dtype
- .shape
- .size
- .ndim
- .T

In [42]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr.dtype)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.T)
print(arr.T.shape)

int64
(2, 3)
6
2
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


### 常用的方法
- .reshape()
- .ravel()
- .prod()
- .sum()
- .mean()
- np.where()
- np.unique()
- np.concatenate()
- np.sort()

In [62]:
# .reshape()「重塑形狀」 與 .ravel()「攤平成一維」
import numpy as np

arr = np.arange(1, 11)
print(arr)
arr = arr.reshape(2, 5)
print(arr)
arr = arr.ravel()
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [59]:
# .prod()「乘積」 與 .sum()「總和」 與 .mean()「平均值」
arr = arr.reshape(2, 5)
print(arr.prod())
print(arr.prod(axis = 0))
print(arr.prod(axis = 1))
print(arr.sum())
print(arr.sum(axis = 0))
print(arr.sum(axis = 1))
print(arr.mean())
print(arr.mean(axis = 0))
print(arr.mean(axis = 1))

3628800
[ 6 14 24 36 50]
[  120 30240]
55
[ 7  9 11 13 15]
[15 40]
5.5
[3.5 4.5 5.5 6.5 7.5]
[3. 8.]


In [60]:
# np.where()「條件取代」
arr = np.arange(1, 11)
print(arr)
arr = np.where(arr > 5, 99, arr)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5 99 99 99 99 99]


In [61]:
# np.concatenate()「水平或垂直合併」
arr_1 = np.arange(1, 11).reshape(2, 5)
arr_2 = np.arange(11, 21).reshape(2, 5)

vertical = np.concatenate([arr_1, arr_2], axis = 0)
print(vertical)
horizontal = np.concatenate([arr_1, arr_2], axis = 1)
print(horizontal)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [75]:
# np.sort()
arr = np.random.randint(1, 11, size = 5)
print(arr)
print(np.sort(arr))

[ 6  6 10  6  7]
[ 6  6  6  7 10]


### ndarray 與基礎線性代數
- 建立向量
- 建立矩陣
- np.transpose() 或 ndarray.T
- np.dot() 或 ndarray.dot()
- np.linalg.inv()

In [1]:
import numpy as np

u = np.array([4, -4, 3]).reshape(-1, 1)
v = np.array([4, 2, 4]).reshape(-1, 1)
print(u)
print(v)

[[ 4]
 [-4]
 [ 3]]
[[4]
 [2]
 [4]]


In [2]:
A = np.arange(1, 5).reshape(2, 2)
print(A)

[[1 2]
 [3 4]]


In [4]:
u_transposed = u.T
print(u_transposed.shape)
u_transposed = np.transpose(u)
print(u_transposed)

(1, 3)
[[ 4 -4  3]]


In [5]:
np.dot(u_transposed, v)

array([[20]])

In [6]:
u_transposed.dot(v)

array([[20]])

In [7]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [8]:
np.dot(A, A_inv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])